// Code generated by goyacc -o spl.go -p spl -v spl.output spl.y. DO NOT EDIT.

//line spl.y:2

package parser

import __yyfmt__ "fmt"

//line spl.y:3

import (
	"github.com/nnsgmsone/nexus/pkg/spl/tree"
	"go/constant"
)

//line spl.y:13

type splSymUnion struct {
	val any
	ss  *tree.Select
}

func (u *splSymUnion) SelectStatement() *tree.Select {
	if u.ss == nil {
		u.ss = new(tree.Select)
	}
	return u.ss
}

func (u *splSymUnion) LimitStatement() *tree.Limit {
	return u.val.(*tree.Limit)
}

func (u *splSymUnion) OrderStatement() *tree.OrderBy {
	return u.val.(*tree.OrderBy)
}

func (u *splSymUnion) StatsStatement() *tree.Stats {
	return u.val.(*tree.Stats)
}

func (u *splSymUnion) WhereStatement() *tree.Where {
	return u.val.(*tree.Where)
}

func (u *splSymUnion) EvalStatement() *tree.Eval {
	return u.val.(*tree.Eval)
}

func (u *splSymUnion) ExtractStatement() *tree.Extract {
	return u.val.(*tree.Extract)
}

func (u *splSymUnion) ImportStatement() *tree.Import {
	return u.val.(*tree.Import)
}

func (u *splSymUnion) extractStatement() tree.ExtractStatement {
	return u.val.(tree.ExtractStatement)
}

func (u *splSymUnion) extractScriptOpt() tree.ExtractScript {
	return u.val.(tree.ExtractScript)
}

func (u *splSymUnion) evalExprStatement() tree.EvalExpr {
	return u.val.(tree.EvalExpr)
}

func (u *splSymUnion) evalExprListStatement() tree.EvalExprList {
	return u.val.(tree.EvalExprList)
}

func (u *splSymUnion) exprStatement() tree.ExprStatement {
	return u.val.(tree.ExprStatement)
}

func (u *splSymUnion) exprStatements() tree.ExprStatements {
	return u.val.(tree.ExprStatements)
}

func (u *splSymUnion) valueStatement() *tree.Value {
	if u.val == nil {
		return nil
	}
	return u.val.(*tree.Value)
}

func (u *splSymUnion) valueStatements() []*tree.Value {
	return u.val.([]*tree.Value)
}

func (u *splSymUnion) statStatement() tree.Stat {
	return u.val.(tree.Stat)
}

func (u *splSymUnion) statListStatement() tree.StatList {
	return u.val.(tree.StatList)
}

func (u *splSymUnion) funcStatement() *tree.FuncExpr {
	return u.val.(*tree.FuncExpr)
}

func (u *splSymUnion) orderListStatement() tree.OrderList {
	return u.val.(tree.OrderList)
}

func (u *splSymUnion) orderStatement() *tree.Order {
	return u.val.(*tree.Order)
}

func (u *splSymUnion) direction() tree.Direction {
	return u.val.(tree.Direction)
}

func (u *splSymUnion) tableName() *tree.TableName {
	return u.val.(*tree.TableName)
}

func (u *splSymUnion) columnName() tree.ColumnName {
	return u.val.(tree.ColumnName)
}

func (u *splSymUnion) columnNameList() tree.ColumnNameList {
	return u.val.(tree.ColumnNameList)
}

func (u *splSymUnion) nameList() tree.NameList {
	return u.val.(tree.NameList)
}

func (u *splSymUnion) name() tree.Name {
	return u.val.(tree.Name)
}

func (u *splSymUnion) setNegative() *tree.Value {
	v, ok := u.val.(*tree.Value)
	if !ok {
		return nil
	}
	iv, _ := constant.Int64Val(v.Value)
	v.Value = constant.MakeInt64(-1 * iv)
	return v
}

//line spl.y:185
type splSymType struct {
	yys   int
	id    int32
	pos   int32
	byt   byte
	str   string
	union splSymUnion
}

const IDENT = 57346
const ICONST = 57347
const FCONST = 57348
const SCONST = 57349
const LESS_EQUALS = 57350
const GREATER_EQUALS = 57351
const NOT_EQUALS = 57352
const AND = 57353
const AS = 57354
const ASC = 57355
const BOOL = 57356
const BY = 57357
const CAST = 57358
const DESC = 57359
const DEDUP = 57360
const DOUBLE = 57361
const EVAL = 57362
const FALSE = 57363
const IMPORT = 57364
const LIMIT = 57365
const LONG = 57366
const LUA = 57367
const LUA_FILE = 57368
const NOT = 57369
const OR = 57370
const ORDER = 57371
const EXTRACT = 57372
const STATS = 57373
const STRING = 57374
const TRUE = 57375
const TYPE = 57376
const WHERE = 57377

var splToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"ICONST",
	"FCONST",
	"SCONST",
	"LESS_EQUALS",
	"GREATER_EQUALS",
	"NOT_EQUALS",
	"AND",
	"AS",
	"ASC",
	"BOOL",
	"BY",
	"CAST",
	"DESC",
	"DEDUP",
	"DOUBLE",
	"EVAL",
	"FALSE",
	"IMPORT",
	"LIMIT",
	"LONG",
	"LUA",
	"LUA_FILE",
	"NOT",
	"OR",
	"ORDER",
	"EXTRACT",
	"STATS",
	"STRING",
	"TRUE",
	"TYPE",
	"WHERE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"'%'",
	"'<'",
	"'>'",
	"'='",
	"'('",
	"')'",
	"'|'",
	"':'",
	"','",
}

var splStatenames = [...]string{}

const splEofCode = 1
const splErrCode = 2
const splInitialStackSize = 16

//line spl.y:520

//line yacctab:1
var splExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 53,
	44, 86,
	-2, 84,
}

const splPrivate = 57344

const splLast = 211

var splAct = [...]uint8{
	53, 72, 111, 42, 44, 109, 36, 56, 135, 132,
	26, 133, 133, 75, 96, 27, 102, 67, 38, 97,
	60, 39, 79, 27, 59, 37, 58, 21, 2, 147,
	71, 89, 90, 91, 60, 95, 94, 77, 73, 78,
	68, 79, 66, 65, 80, 4, 76, 23, 24, 92,
	81, 82, 83, 84, 85, 93, 125, 74, 78, 81,
	82, 83, 84, 85, 86, 87, 88, 63, 27, 137,
	134, 101, 83, 84, 85, 60, 60, 38, 100, 73,
	59, 112, 113, 108, 37, 114, 115, 116, 117, 118,
	119, 120, 121, 122, 123, 124, 25, 60, 128, 79,
	127, 129, 107, 60, 131, 106, 29, 73, 28, 47,
	48, 49, 70, 130, 30, 99, 79, 136, 98, 64,
	57, 62, 69, 34, 33, 51, 30, 28, 47, 48,
	49, 41, 28, 78, 46, 139, 138, 50, 146, 57,
	55, 45, 54, 104, 51, 31, 32, 105, 52, 126,
	41, 140, 28, 47, 48, 49, 50, 31, 32, 141,
	45, 35, 43, 40, 57, 61, 103, 52, 110, 51,
	28, 47, 48, 49, 12, 41, 22, 5, 143, 11,
	10, 50, 57, 144, 9, 45, 8, 51, 142, 19,
	7, 14, 52, 20, 15, 6, 145, 3, 1, 50,
	16, 13, 17, 45, 0, 0, 18, 0, 0, 0,
	52,
}

var splPact = [...]int16{
	-18, -1000, 171, -19, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 22, 128, 121, 109, 128, 148, 128,
	114, 171, 128, 0, -1, -31, -1000, -3, -1000, -1000,
	-1000, 117, 107, 128, 42, -2, -1000, -7, -1000, 30,
	-1000, 148, 23, -1000, -1000, 166, -1000, -1000, -1000, -1000,
	-1000, -1000, 148, -1000, -1000, -1000, -8, -9, -34, -1000,
	-1000, -29, -1000, -1000, -31, 111, 108, 128, 148, -1000,
	-1000, -32, -1000, 130, 128, 128, 128, 123, 148, 148,
	-1000, 166, 166, 166, 166, 166, 166, 166, 166, 166,
	166, 166, 34, 11, 104, 148, 128, 106, -1000, -1000,
	-1000, 30, 128, -1000, -1000, -1000, -32, -34, -1000, -36,
	58, 30, 88, -1000, 34, 34, -1000, -1000, -1000, 14,
	14, 14, 14, 14, 14, -1000, -1000, -37, 105, -1000,
	-1000, -1000, 57, 148, 128, -1000, 164, 128, 30, -1000,
	-16, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
}

var splPgo = [...]uint8{
	0, 198, 197, 45, 195, 190, 186, 184, 180, 179,
	177, 176, 174, 166, 96, 10, 0, 7, 4, 26,
	165, 30, 5, 2, 3, 163, 162, 1, 161, 6,
	159, 151, 106, 142, 140, 134,
}

var splR1 = [...]int8{
	0, 1, 2, 2, 3, 3, 3, 3, 3, 3,
	3, 3, 10, 11, 11, 4, 8, 5, 9, 7,
	7, 12, 20, 20, 14, 14, 15, 28, 28, 29,
	29, 29, 29, 6, 6, 21, 21, 27, 13, 13,
	13, 22, 22, 23, 23, 23, 23, 23, 24, 24,
	24, 24, 24, 24, 24, 24, 24, 25, 25, 25,
	25, 25, 25, 26, 26, 26, 26, 26, 26, 32,
	32, 32, 35, 35, 33, 33, 34, 31, 30, 30,
	30, 30, 19, 19, 18, 16, 17,
}

var splR2 = [...]int8{
	0, 2, 1, 3, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 3, 3, 2, 2, 2, 2, 2,
	4, 2, 1, 3, 1, 3, 3, 1, 3, 6,
	5, 3, 4, 3, 4, 1, 3, 2, 1, 1,
	0, 1, 3, 1, 2, 3, 3, 1, 1, 1,
	2, 3, 3, 3, 3, 3, 1, 3, 3, 3,
	3, 3, 3, 1, 1, 1, 1, 1, 3, 1,
	2, 2, 1, 1, 3, 4, 6, 1, 1, 1,
	1, 1, 1, 3, 1, 1, 1,
}

var splChk = [...]int16{
	-1000, -1, 46, -2, -3, -10, -4, -5, -6, -7,
	-8, -9, -12, 30, 20, 23, 29, 31, 35, 18,
	22, 46, -11, 25, 26, -14, -15, -16, 4, -32,
	5, 36, 37, 15, -32, -28, -29, -17, -16, -23,
	-25, 27, -24, -26, -18, 37, -35, 5, 6, 7,
	33, 21, 44, -16, -33, -34, -17, 16, -19, -18,
	-16, -20, 7, -3, -14, 43, 43, 48, 43, 5,
	5, -21, -27, -18, 15, 15, 48, 44, 28, 11,
	-23, 36, 37, 38, 39, 40, 41, 42, 43, 8,
	9, 10, -24, -23, 44, 44, 48, 48, 7, 7,
	-15, -23, 48, -13, 13, 17, -21, -19, -29, -22,
	45, -23, -23, -23, -24, -24, -24, -24, -24, -24,
	-24, -24, -24, -24, -24, 45, 45, -22, -23, -18,
	7, -27, 45, 48, 12, 45, 12, 12, -23, -16,
	-31, -30, 24, 14, 19, 32, -16, 45,
}

var splDef = [...]int8{
	0, -2, 0, 1, 2, 4, 5, 6, 7, 8,
	9, 10, 11, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 15, 24, 0, 85, 17,
	69, 0, 0, 0, 0, 19, 27, 0, 86, 16,
	43, 0, 47, 48, 49, 0, 56, 63, 64, 65,
	66, 67, 0, -2, 72, 73, 0, 0, 18, 82,
	84, 21, 22, 3, 12, 0, 0, 0, 0, 70,
	71, 33, 35, 40, 0, 0, 0, 0, 0, 0,
	44, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 50, 0, 0, 0, 0, 0, 13, 14,
	25, 26, 0, 37, 38, 39, 34, 20, 28, 0,
	31, 41, 45, 46, 51, 52, 53, 54, 55, 57,
	58, 59, 60, 61, 62, 68, 74, 0, 0, 83,
	23, 36, 32, 0, 0, 75, 0, 0, 42, 30,
	0, 77, 78, 79, 80, 81, 29, 76,
}

var splTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 40, 3, 3,
	44, 45, 38, 36, 48, 37, 3, 39, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 47, 3,
	41, 43, 42, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 46,
}

var splTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35,
}

var splTok3 = [...]int8{
	0,
}

var splErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	splDebug        = 0
	splErrorVerbose = false
)

type splLexer interface {
	Lex(lval *splSymType) int
	Error(s string)
}

type splParser interface {
	Parse(splLexer) int
	Lookahead() int
}

type splParserImpl struct {
	lval  splSymType
	stack [splInitialStackSize]splSymType
	char  int
}

func (p *splParserImpl) Lookahead() int {
	return p.char
}

func splNewParser() splParser {
	return &splParserImpl{}
}

const splFlag = -1000

func splTokname(c int) string {
	if c >= 1 && c-1 < len(splToknames) {
		if splToknames[c-1] != "" {
			return splToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func splStatname(s int) string {
	if s >= 0 && s < len(splStatenames) {
		if splStatenames[s] != "" {
			return splStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func splErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !splErrorVerbose {
		return "syntax error"
	}

	for _, e := range splErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + splTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(splPact[state])
	for tok := TOKSTART; tok-1 < len(splToknames); tok++ {
		if n := base + tok; n >= 0 && n < splLast && int(splChk[int(splAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if splDef[state] == -2 {
		i := 0
		for splExca[i] != -1 || int(splExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; splExca[i] >= 0; i += 2 {
			tok := int(splExca[i])
			if tok < TOKSTART || splExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if splExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += splTokname(tok)
	}
	return res
}

func spllex1(lex splLexer, lval *splSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(splTok1[0])
		goto out
	}
	if char < len(splTok1) {
		token = int(splTok1[char])
		goto out
	}
	if char >= splPrivate {
		if char < splPrivate+len(splTok2) {
			token = int(splTok2[char-splPrivate])
			goto out
		}
	}
	for i := 0; i < len(splTok3); i += 2 {
		token = int(splTok3[i+0])
		if token == char {
			token = int(splTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(splTok2[1]) /* unknown char */
	}
	if splDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", splTokname(token), uint(char))
	}
	return char, token
}

func splParse(spllex splLexer) int {
	return splNewParser().Parse(spllex)
}

func (splrcvr *splParserImpl) Parse(spllex splLexer) int {
	var spln int
	var splVAL splSymType
	var splDollar []splSymType
	_ = splDollar // silence set and not used
	splS := splrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	splstate := 0
	splrcvr.char = -1
	spltoken := -1 // splrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		splstate = -1
		splrcvr.char = -1
		spltoken = -1
	}()
	splp := -1
	goto splstack

ret0:
	return 0

ret1:
	return 1

splstack:
	/* put a state and value onto the stack */
	if splDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", splTokname(spltoken), splStatname(splstate))
	}

	splp++
	if splp >= len(splS) {
		nyys := make([]splSymType, len(splS)*2)
		copy(nyys, splS)
		splS = nyys
	}
	splS[splp] = splVAL
	splS[splp].yys = splstate

splnewstate:
	spln = int(splPact[splstate])
	if spln <= splFlag {
		goto spldefault /* simple state */
	}
	if splrcvr.char < 0 {
		splrcvr.char, spltoken = spllex1(spllex, &splrcvr.lval)
	}
	spln += spltoken
	if spln < 0 || spln >= splLast {
		goto spldefault
	}
	spln = int(splAct[spln])
	if int(splChk[spln]) == spltoken { /* valid shift */
		splrcvr.char = -1
		spltoken = -1
		splVAL = splrcvr.lval
		splstate = spln
		if Errflag > 0 {
			Errflag--
		}
		goto splstack
	}

spldefault:
	/* default state action */
	spln = int(splDef[splstate])
	if spln == -2 {
		if splrcvr.char < 0 {
			splrcvr.char, spltoken = spllex1(spllex, &splrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if splExca[xi+0] == -1 && int(splExca[xi+1]) == splstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			spln = int(splExca[xi+0])
			if spln < 0 || spln == spltoken {
				break
			}
		}
		spln = int(splExca[xi+1])
		if spln < 0 {
			goto ret0
		}
	}
	if spln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			spllex.Error(splErrorMessage(splstate, spltoken))
			Nerrs++
			if splDebug >= 1 {
				__yyfmt__.Printf("%s", splStatname(splstate))
				__yyfmt__.Printf(" saw %s\n", splTokname(spltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for splp >= 0 {
				spln = int(splPact[splS[splp].yys]) + splErrCode
				if spln >= 0 && spln < splLast {
					splstate = int(splAct[spln]) /* simulate a shift of "error" */
					if int(splChk[splstate]) == splErrCode {
						goto splstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if splDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", splS[splp].yys)
				}
				splp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if splDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", splTokname(spltoken))
			}
			if spltoken == splEofCode {
				goto ret1
			}
			splrcvr.char = -1
			spltoken = -1
			goto splnewstate /* try again in the same state */
		}
	}

	/* reduction by production spln */
	if splDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", spln, splStatname(splstate))
	}

	splnt := spln
	splpt := splp
	_ = splpt // guard against "declared and not used"

	splp -= int(splR2[spln])
	// splp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if splp+1 >= len(splS) {
		nyys := make([]splSymType, len(splS)*2)
		copy(nyys, splS)
		splS = nyys
	}
	splVAL = splS[splp+1]

	/* consult goto table to find next state */
	spln = int(splR1[spln])
	splg := int(splPgo[spln])
	splj := splg + splS[splp].yys + 1

	if splj >= splLast {
		splstate = int(splAct[splg])
	} else {
		splstate = int(splAct[splj])
		if int(splChk[splstate]) != -spln {
			splstate = int(splAct[splg])
		}
	}
	// dummy call; replaced with literal code
	switch splnt {

	case 1:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:248
		{
			spllex.(*lexer).SetStmt(splDollar[2].union.SelectStatement())
		}
	case 2:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:253
		{
			splVAL.union.val = splDollar[1].union.SelectStatement()
		}
	case 3:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:257
		{
			as, bs := splDollar[1].union.SelectStatement(), splDollar[3].union.SelectStatement()
			as.Cs = append(as.Cs, bs.Cs...)
			splVAL.union.val = as
		}
	case 4:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:264
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.ExtractStatement())
		}
	case 5:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:269
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.EvalStatement())
		}
	case 6:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:274
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.LimitStatement())
		}
	case 7:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:279
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.OrderStatement())
		}
	case 8:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:284
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.StatsStatement())
		}
	case 9:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:289
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.WhereStatement())
		}
	case 10:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:294
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.StatsStatement())
		}
	case 11:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:299
		{
			ss := splVAL.union.SelectStatement()
			ss.Cs = append(ss.Cs, splDollar[1].union.ImportStatement())
		}
	case 12:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:305
		{
			splVAL.union.val = &tree.Extract{Script: splDollar[2].union.extractScriptOpt(), Es: splDollar[3].union.evalExprListStatement()}
		}
	case 13:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:310
		{
			splVAL.union.val = tree.ExtractScript{Lua: splDollar[3].union.valueStatement()}
		}
	case 14:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:314
		{
			splVAL.union.val = tree.ExtractScript{LuaFile: splDollar[3].union.valueStatement()}
		}
	case 15:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:320
		{
			splVAL.union.val = &tree.Eval{splDollar[2].union.evalExprListStatement()}
		}
	case 16:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:325
		{
			splVAL.union.val = &tree.Where{splDollar[2].union.exprStatement()}
		}
	case 17:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:330
		{
			splVAL.union.val = &tree.Limit{Count: splDollar[2].union.valueStatement()}
		}
	case 18:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:335
		{
			splVAL.union.val = &tree.Stats{By: splDollar[2].union.columnNameList()}
		}
	case 19:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:341
		{
			splVAL.union.val = &tree.Stats{Ss: splDollar[2].union.statListStatement()}
		}
	case 20:
		splDollar = splS[splpt-4 : splpt+1]
//line spl.y:345
		{
			splVAL.union.val = &tree.Stats{Ss: splDollar[2].union.statListStatement(), By: splDollar[4].union.columnNameList()}
		}
	case 21:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:350
		{
			splVAL.union.val = &tree.Import{Paths: splDollar[2].union.valueStatements()}
		}
	case 22:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:355
		{
			splVAL.union.val = []*tree.Value{splDollar[1].union.valueStatement()}
		}
	case 23:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:359
		{
			splVAL.union.val = append(splDollar[1].union.valueStatements(), splDollar[3].union.valueStatement())
		}
	case 24:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:364
		{
			splVAL.union.val = tree.EvalExprList{splDollar[1].union.evalExprStatement()}
		}
	case 25:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:368
		{
			splVAL.union.val = append(splDollar[1].union.evalExprListStatement(), splDollar[3].union.evalExprStatement())
		}
	case 26:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:373
		{
			splVAL.union.val = tree.EvalExpr{As: tree.Name(splDollar[1].str), E: splDollar[3].union.exprStatement()}
		}
	case 27:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:378
		{
			splVAL.union.val = tree.StatList{splDollar[1].union.statStatement()}
		}
	case 28:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:382
		{
			splVAL.union.val = append(splDollar[1].union.statListStatement(), splDollar[3].union.statStatement())
		}
	case 29:
		splDollar = splS[splpt-6 : splpt+1]
//line spl.y:387
		{
			splVAL.union.val = tree.Stat{F: tree.Name(splDollar[1].str), Es: splDollar[3].union.exprStatements(), As: tree.Name(splDollar[6].str)}
		}
	case 30:
		splDollar = splS[splpt-5 : splpt+1]
//line spl.y:391
		{
			splVAL.union.val = tree.Stat{F: tree.Name(splDollar[1].str), As: tree.Name(splDollar[5].str)}
		}
	case 31:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:395
		{
			splVAL.union.val = tree.Stat{F: tree.Name(splDollar[1].str)}
		}
	case 32:
		splDollar = splS[splpt-4 : splpt+1]
//line spl.y:399
		{
			splVAL.union.val = tree.Stat{F: tree.Name(splDollar[1].str), Es: splDollar[3].union.exprStatements()}
		}
	case 33:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:404
		{
			splVAL.union.val = &tree.OrderBy{Orders: splDollar[3].union.orderListStatement(), Limit: nil}
		}
	case 34:
		splDollar = splS[splpt-4 : splpt+1]
//line spl.y:408
		{
			splVAL.union.val = &tree.OrderBy{Limit: splDollar[2].union.valueStatement(), Orders: splDollar[4].union.orderListStatement()}
		}
	case 35:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:413
		{
			splVAL.union.val = tree.OrderList{splDollar[1].union.orderStatement()}
		}
	case 36:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:417
		{
			splVAL.union.val = append(splDollar[1].union.orderListStatement(), splDollar[3].union.orderStatement())
		}
	case 37:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:422
		{
			splVAL.union.val = &tree.Order{
				E:    splDollar[1].union.exprStatement(),
				Type: splDollar[2].union.direction(),
			}
		}
	case 38:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:429
		{
			splVAL.union.val = tree.Ascending
		}
	case 39:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:430
		{
			splVAL.union.val = tree.Descending
		}
	case 40:
		splDollar = splS[splpt-0 : splpt+1]
//line spl.y:431
		{
			splVAL.union.val = tree.DefaultDirection
		}
	case 41:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:435
		{
			splVAL.union.val = tree.ExprStatements{splDollar[1].union.exprStatement()}
		}
	case 42:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:436
		{
			splVAL.union.val = append(splDollar[1].union.exprStatements(), splDollar[3].union.exprStatement())
		}
	case 43:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:438
		{
			splVAL.union.val = splDollar[1].union.exprStatement()
		}
	case 44:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:439
		{
			splVAL.union.val = &tree.FuncExpr{Name: "not", Args: tree.ExprStatements{splDollar[2].union.exprStatement()}}
		}
	case 45:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:440
		{
			splVAL.union.val = &tree.FuncExpr{Name: "or", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 46:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:441
		{
			splVAL.union.val = &tree.FuncExpr{Name: "and", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 47:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:442
		{
			splVAL.union.val = splDollar[1].union.exprStatement()
		}
	case 48:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:444
		{
			splVAL.union.val = splDollar[1].union.exprStatement()
		}
	case 49:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:445
		{
			splVAL.union.val = splDollar[1].union.columnName()
		}
	case 50:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:446
		{
			splVAL.union.val = &tree.FuncExpr{Name: "-", Args: tree.ExprStatements{splDollar[2].union.exprStatement()}}
		}
	case 51:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:447
		{
			splVAL.union.val = &tree.FuncExpr{Name: "+", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 52:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:448
		{
			splVAL.union.val = &tree.FuncExpr{Name: "-", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 53:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:449
		{
			splVAL.union.val = &tree.FuncExpr{Name: "*", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 54:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:450
		{
			splVAL.union.val = &tree.FuncExpr{Name: "/", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 55:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:451
		{
			splVAL.union.val = &tree.FuncExpr{Name: "%", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 56:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:452
		{
			splVAL.union.val = splDollar[1].union.funcStatement()
		}
	case 57:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:454
		{
			splVAL.union.val = &tree.FuncExpr{Name: "<", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 58:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:455
		{
			splVAL.union.val = &tree.FuncExpr{Name: ">", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 59:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:456
		{
			splVAL.union.val = &tree.FuncExpr{Name: "=", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 60:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:457
		{
			splVAL.union.val = &tree.FuncExpr{Name: "<=", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 61:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:458
		{
			splVAL.union.val = &tree.FuncExpr{Name: ">=", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 62:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:459
		{
			splVAL.union.val = &tree.FuncExpr{Name: "<>", Args: tree.ExprStatements{splDollar[1].union.exprStatement(), splDollar[3].union.exprStatement()}}
		}
	case 63:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:461
		{
			splVAL.union.val = splDollar[1].union.valueStatement()
		}
	case 64:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:462
		{
			splVAL.union.val = splDollar[1].union.valueStatement()
		}
	case 65:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:463
		{
			splVAL.union.val = splDollar[1].union.valueStatement()
		}
	case 66:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:464
		{
			splVAL.union.val = &tree.Value{Value: constant.MakeBool(true)}
		}
	case 67:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:465
		{
			splVAL.union.val = &tree.Value{Value: constant.MakeBool(false)}
		}
	case 68:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:466
		{
			splVAL.union.val = &tree.ParenExpr{splDollar[2].union.exprStatement()}
		}
	case 69:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:468
		{
			splVAL.union.val = splDollar[1].union.valueStatement()
		}
	case 70:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:469
		{
			splVAL.union.val = splDollar[2].union.valueStatement()
		}
	case 71:
		splDollar = splS[splpt-2 : splpt+1]
//line spl.y:470
		{
			splVAL.union.val = splDollar[2].union.setNegative()
		}
	case 72:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:473
		{
			splVAL.union.val = splDollar[1].union.funcStatement()
		}
	case 73:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:477
		{
			splVAL.union.val = splDollar[1].union.funcStatement()
		}
	case 74:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:482
		{
			splVAL.union.val = &tree.FuncExpr{Name: splDollar[1].str}
		}
	case 75:
		splDollar = splS[splpt-4 : splpt+1]
//line spl.y:486
		{
			splVAL.union.val = &tree.FuncExpr{Name: splDollar[1].str, Args: splDollar[3].union.exprStatements()}
		}
	case 76:
		splDollar = splS[splpt-6 : splpt+1]
//line spl.y:491
		{
			splVAL.union.val = &tree.FuncExpr{Name: "cast", Args: tree.ExprStatements{splDollar[3].union.exprStatement(), splDollar[5].union.exprStatement()}}
		}
	case 77:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:495
		{
			splVAL.union.val = splDollar[1].union.exprStatement()
		}
	case 78:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:497
		{
			splVAL.union.val = &tree.Value{Value: constant.MakeInt64(0)}
		}
	case 79:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:498
		{
			splVAL.union.val = &tree.Value{Value: constant.MakeBool(true)}
		}
	case 80:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:499
		{
			splVAL.union.val = &tree.Value{Value: constant.MakeFloat64(0)}
		}
	case 81:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:500
		{
			splVAL.union.val = &tree.Value{Value: constant.MakeString("")}
		}
	case 82:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:503
		{
			splVAL.union.val = tree.ColumnNameList{splDollar[1].union.columnName()}
		}
	case 83:
		splDollar = splS[splpt-3 : splpt+1]
//line spl.y:507
		{
			splVAL.union.val = append(splDollar[1].union.columnNameList(), splDollar[3].union.columnName())
		}
	case 84:
		splDollar = splS[splpt-1 : splpt+1]
//line spl.y:512
		{
			splVAL.union.val = tree.ColumnName{Path: tree.Name(splDollar[1].str)}
		}
	}
	goto splstack /* stack new state and value */
}
